name: Build icml from all MDs
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/core:2.9
        with:
          args: --output=output/result.icml ${{ env.FILELIST }} --standalone
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
